# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131eop2hx9jEHlG3aDstOAqf_wsqnG7kL
"""

a = 5
b = input()
try: # это конструкция, это наша с Мишей aka @omiTelega aka Михаил Овчарук шиза, которая проверяет какой тип переменной ввел пользователь, целочисленное, дробь и т.д. чисто теоретически это можно ветвить дальше
    b = float(b) # пробуем преобразовать введеное число в дробное
    c = b # сохраняем его значение в доп переменную
    b = int(b) # преобразуем исходное число в int, если число было дробным, то дробная часть отсекается
    if b==c:
        #print("Целое число")
        print (a*b)
    else:
        print(a*c)
except ValueError: # если преобразование не удалось и нам выкидывает ошибку то значит, что там есть либо символы которые использованы некорректно либо буквы
    print("Буквы")

a = input()
b = input()
while not a.isdigit(): #проверка что введеное значение это число, это было написано до того как шиза появилась и я не стал переделывать
  a = input()
while not b.isdigit():
  b = input()
c = ((int(a)+int(b))**2)
print(c)

a = 10
b = 15
c = input()
while not c.isdigit():
  c = input()
X = ((a+b)/int(c))
print(X)

a = input()
b = input()
while not a.isdigit():
  a = input()
while not b.isdigit():
  b = input()
c = (int(a)**2)+(2*int(a)*int(b))+(int(b)**2)
print(c)
print(f"c = ({a}**2)+(2*{a}*{b})+({b}**2)")

from math import sqrt

a = input()
b = input()
c = input()
while not a.isdigit() or not b.isdigit() or not c.isdigit:
  a = input()
  b = input()
  c = input()
a = int(a)
b = int(b)
c = int(c)
if a+b > c and a+c>b and b+c>a and a>0 and b>0 and c>0:
    P = a+b+c
    p = ((a+b+c)/2)
    S = (sqrt(p*(p-a)*(p-b)*(p-c)))
    print(f"P = {P} S = {S}")
else:
    print("треугольник не существует")

a = input()
b = input()
while not a.isdigit():
  a = input()
while not b.isdigit():
  b = input()
a = int(a)
b = int(b)
print(f"((({a}**3+14)/5)*{b})")

a = input()
n = input()
while not a.isdigit():
  a = input()
while not n.isdigit():
  n = input()
P = int(a)**2
print(P//int(n))

def check(b): #шиза развивается
    try:
        b = float(b)
        c = b
        b = int(b)
        if b==c:
            #print("Целое число")
            return 0 # если введенное число целое то функция вернет 0

        else:
            #print("Дробное число")
            return 1 # если введенное число дробное то функция вернет 1
    except ValueError:
        #print("Буквы")
        return 2 # если введенное, не число или не корректно введенное число, то функция вернет 2


def case_1(): # программа для выполнения первого задания
    c = input("Введите дробное число ")
    if check(c) == 1: # проверка что введенное пользователем значение это дробное число
        return c # возвращает введенное число
    else:
        print("Ввод не корректен.")
        return case_1() # если ввод не корректен, то мы возвращаемся к вводу числа



def case_2_and_3():
    c = input("Введите натуральное число ")
    if check(c) == 0 and int(c)>=0: # проверка натурального числа, если бы заданий было больше в принципе можео было бы это проверять в функции check()
        return c
    else:
        print("Ввод не корректен.")
        return case_2_and_3()




value=0 # чисто технические это подобие интерфейса созданное через бесконечный цикл, value отвечает за то какой блок кода начнет работать
Exit = False
while Exit == False:
    match value:
        case 0: # выбор действия, стартовый интерфейс
            print("Деление дробных чисел — 1")
            print("Умножение натуральных чисел — 2")
            print("Остаток от деления натуральных чисел — 3")
            print("Завершить выполнение — 4")
            userInputComand = input("Выберите действие: ")
            print("\n")

            if userInputComand == "1" or userInputComand == "2" or userInputComand == "3" or userInputComand == "4": # проверка корректности ввода
                value = int(userInputComand)
            else:
                print("Некорректная команда!","\n")
                value = 0
        case 1: # в зависимости от выбора пользователя запускается определенная задача
            result0 = case_1() # см. case_1
            a = result0

            result1 = case_1()
            b = result1

            print(float(a)//float(b))
            print("\n")
            value = 0
        case 2:
            result0 = case_2_and_3()
            a1 = result0

            result1 = case_2_and_3()
            b1 = result1

            print (int(a1)*int(b1))
            print("\n")
            value = 0
        case 3:
            result0 = case_2_and_3()
            a2 = result0

            result1 = case_2_and_3()
            b2 = result1

            print (int(a2)%int(b2))
            print("\n")
            value = 0
        case 4:
            Exit = True

sec = input()
while not sec.isdigit():
  sec = input()
sec = int(sec)
if sec>=0:
  min = sec/60
  hours = min/60
  days = hours/24
  print(min,hours,days)
else:
  print("Количество секунд должно быть положительным")

n = input("Введите целое число: ")
while not n.isdigit():
  n = input()
n = int(n)
res = n + (n**2)+(n**3)
print(res)