# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWDi1ybVHxW7fClp38QHu-9F6WxLZsVN
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

fahrenheit = np.array([-100, -50, 0, 32, 50, 100, 150, 200, 212, 300]).reshape(-1, 1)
kelvin = (fahrenheit - 32) * 5/9 + 273.15

plt.figure(figsize=(10, 6))
plt.scatter(fahrenheit, kelvin, label='Экспериментальные значения', color='blue', marker='o')
plt.xlabel('Фаренгейты (°F)')
plt.ylabel('Кельвины (K)')
plt.title('Зависимость температуры в Кельвинах от Фаренгейтов')
plt.grid(True)
plt.legend()
plt.show()

lr = LinearRegression()
lr.fit(fahrenheit, kelvin)

test_values = [[-40], [77], [212], [500]]
predictions = lr.predict(test_values)

print("\nПредсказанные значения:")
for f, k in zip(test_values, predictions):
    print(f"{f[0]}°F -> {k[0]:.2f}K")


print("\nСравнение с реальными:")
for f_val in test_values:
    real_k = (f_val[0] - 32) * 5/9 + 273.15
    pred_k = lr.predict([f_val])[0][0]
    print(f"{f_val[0]}°F: реальное = {real_k:.2f}K, предсказанное = {pred_k:.2f}K")

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
categories = ['Python', 'Java', 'JavaScript', 'C++', 'C#']
popularity = [65, 48, 56, 38, 30]
plt.bar(categories, popularity, color=['red', 'blue', 'yellow', 'green', 'purple'])
plt.title('Популярность языков программирования')
plt.xlabel('Язык')
plt.ylabel('Популярность (%)')
plt.grid(axis='y')

plt.subplot(1, 3, 2)
labels = ['Windows', 'macOS', 'Linux', 'Другие']
sizes = [75, 15, 5, 5]
colors = ['#ff9999', '#66b3ff', '#99ff99', '#ffcc99']
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.title('Доля операционных систем')

plt.subplot(1, 3, 3)
data = np.random.normal(170, 10, 1000)
plt.hist(data, bins=30, color='skyblue', edgecolor='black', alpha=0.7)
plt.title('Распределение роста (гистограмма)')
plt.xlabel('Рост (см)')
plt.ylabel('Частота')

plt.tight_layout()
plt.show()

import math
journal_number = 10
phone_memory = 256

print("1. Число Эйлера (e):", math.e)
print("2. Число Пи (π):", math.pi)
print("3. NaN:", math.nan)
print(f"4. Факториал числа {journal_number}:", math.factorial(journal_number))
print(f"5. Наибольший общий делитель ({journal_number} и {phone_memory}):",
      math.gcd(journal_number, phone_memory))

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np
from scipy.spatial import ConvexHull

def draw_d20():
    phi = (1 + np.sqrt(5)) / 2

    vertices = np.array([
        [0, 1, phi], [0, -1, phi], [0, 1, -phi], [0, -1, -phi],
        [1, phi, 0], [-1, phi, 0], [1, -phi, 0], [-1, -phi, 0],
        [phi, 0, 1], [-phi, 0, 1], [phi, 0, -1], [-phi, 0, -1]
    ])


    hull = ConvexHull(vertices)
    faces = vertices[hull.simplices]


    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(111, projection='3d')
    ax.set_title("D20 (Икосаэдр)", fontsize=20)

    poly3d = Poly3DCollection(faces, facecolors='crimson', linewidths=1, edgecolors='white', alpha=0.8)
    ax.add_collection3d(poly3d)

    ax.set_axis_off()

    limit = np.max(np.abs(vertices))
    ax.set_xlim(-limit, limit)
    ax.set_ylim(-limit, limit)
    ax.set_zlim(-limit, limit)

    ax.set_box_aspect([1, 1, 1])

    plt.tight_layout()
    plt.show()


draw_d20()

# TensorFlow — это сквозная платформа с открытым исходным кодом для машинного обучения.
# Keras — это высокоуровневый API для нейросетей, работающий поверх TensorFlow. Он упрощает создание моделей.
import tensorflow as tf
from tensorflow import keras

# NumPy (Numerical Python) — фундаментальная библиотека для научных вычислений.
# Она позволяет эффективно работать с многомерными массивами (матрицами), что необходимо для обработки изображений.
import numpy as np

# Matplotlib — самая популярная библиотека для визуализации данных в Python.
# Pyplot — это модуль matplotlib, который предоставляет интерфейс, для построения графиков и отображения изображений.
import matplotlib.pyplot as plt

print("Библиотеки успешно импортированы.")


# Загружаем датасет Fashion MNIST
# Он разделен на:
# train_images, train_labels — данные для обучения (60 000 картинок)
# test_images, test_labels — данные для проверки (10 000 картинок)
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = [
    'T-shirt/top (Футболка)',
    'Trouser (Брюки)',
    'Pullover (Пуловер)',
    'Dress (Платье)',
    'Coat (Пальто)',
    'Sandal (Сандалии)',
    'Shirt (Рубашка)',
    'Sneaker (Кроссовки)',
    'Bag (Сумка)',
    'Ankle boot (Ботильоны)'
]

train_images = train_images / 255.0
test_images = test_images / 255.0

print(f"Размер тренировочных данных: {train_images.shape}")
print(f"Количество классов: {len(class_names)}")


plt.figure(figsize=(10, 5))
for i in range(10):
    idx = np.where(train_labels == i)[0][0]

    plt.subplot(2, 5, i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[idx], cmap=plt.cm.binary)
    plt.xlabel(class_names[i])

plt.suptitle("Все типы вещей в датасете Fashion MNIST")
plt.show()

predictions = model.predict(test_images)

def plot_image(i, predictions_array, true_label, img):
    predictions_array, true_label, img = predictions_array, true_label[i], img[i]
    plt.grid(False)
    plt.xticks([])
    plt.yticks([])

    plt.imshow(img, cmap=plt.cm.binary)

    predicted_label = np.argmax(predictions_array)
    if predicted_label == true_label:
        color = 'blue'
    else:
        color = 'red'

    plt.xlabel("{} {:2.0f}% ({})".format(class_names[predicted_label],
                                100*np.max(predictions_array),
                                class_names[true_label]),
                                color=color)

num_rows = 3
num_cols = 5
num_images = num_rows * num_cols
plt.figure(figsize=(2*2*num_cols, 2*num_rows))

import random
random_indices = random.sample(range(len(test_images)), num_images)

for i, idx in enumerate(random_indices):
    plt.subplot(num_rows, num_cols, i+1)
    plot_image(idx, predictions[idx], test_labels, test_images)

plt.suptitle("Результаты распознавания (Предсказание vs Реальность)")
plt.tight_layout()
plt.show()# lab 6
