# -*- coding: utf-8 -*-
"""lab 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaispaYBO3d9-P5TA9ZAUkSqmw3uP0RA
"""

try:
  month = int(input("Введите номер месяца "))
  if month == 1:
    print("Январь")
  elif month == 2:
    print("Февраль")
  elif month == 3:
    print("Март")
  elif month == 4:
    print("Апрель")
  elif month == 5:
    print("Май")
  elif month == 6:
    print("Июнь")
  elif month == 7:
    print("Июль")
  elif month == 8:
    print("Август")
  elif month == 9:
    print("Сентябрь")
  elif month == 10:
    print("Октябрь")
  elif month == 11:
    print("Ноябрь")
  elif month == 12:
    print("Декабрь")
  else:
    print("Введен некорректный номер месяца")
except:
  print("Введено некорректное значение")

num = input("Введите число ")
try:
  if int(num) % 2 == 0:
    print("Число четное")
  else:
    print("Число нечетное")
except:
  print("Введено некорректное значение")

try:
  N = int(input("Введите число "))
  if N < 40:
    print("not stonks")
  elif N > 40:
    print("stonks")
  else:
    print("Ты ввел 40!!")
except:
  print("Введено некорректное значение")

def is_year_leap(N):
  if N % 4 == 0:
    return True
  else:
    return False
try:
  Year = int(input("Введите год "))
  print(is_year_leap(Year))
except:
  print("Введено некорректное значение ")

def is_prime(n):
  if n <= 1:
    return False
  elif n // 1 and n // n:
    return True
  else:
    return False

try:
  num = int(input("Введите число "))
  print(is_prime(num))
except:
  print("Введено некорректное значение")

from numpy import real

a = float((input("Введите число ")))
b = float((input("Введите число ")))
p = (-138/2)**1.3
p = real(p)
if a*3.6 == b or p <= b <=(-69/(28**5.1)*4):
  a,b = b,a
  print(f"Значение a = {a} Значение b = {b}")
else:
  print(f"Значение a = {a} Значение b = {b}")

print("Введите 5 чисел:")
numbers = []
range_count = 0
negative_count = 0
even_count = 0
for i in range(5):
    num = float(input(f"Число {i+1}: "))
    numbers.append(num)

if len(numbers) == len(set(numbers)):
  print("Все числа уникальны")
else:
  print("Числа неуникальны")
for i in numbers:
  if i % 2 == 0:
    even_count+=1
  if i < 0:
    negative_count+=1
  if -256 <= i <= 1024:
    range_count+=1
print(f'Четных чисел: {even_count}')
print(f'Отрицательных чисел: {negative_count}')
print(f'Чисел которые входят в промежуток: {range_count}')

a = float(input("Введите a: "))
b = float(input("Введите b: "))
c = float(input("Введите c: "))

if c == -3:
    print("Знаменатель не может быть равен нулю")
else:
    result = ((a**2 + b**3) / (c + 3)) / 4
    print(result)
    if result == int(result):
        if int(result) % 2 == 0:
            print("Ответ четное число")
        else:
            print("Ответ нечетное число")
    else:
        print("Ответ дробный")